#!/usr/bin/env bash

set -euo pipefail

DEFAULT_KUBECONFIG=/path/to/a/default/kubeconfig

if [ -z "${1:-}" ]; then
  echo "Usage: prowlog POD_NAME"
  exit 1
fi

kubeconfig="${KUBECONFIG:-$DEFAULT_KUBECONFIG}"

dj --kubeconfig "$kubeconfig" logs "$1"
